### ISSUE TITLE
event ID 61f71b770cab4a47b75349e2f0f177ae

### ISSUE THREAD

**Issue by nickyb01** [davwheat/rail-announcements#178]
EncodingError: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data Error: Failed to execute 'decodeAudioData' on 
at K (https://railannouncements.co.uk/9f38c194-39fbb7e3538bbd963356.js:1:2529) at u (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:1527) at m (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:4325) at div at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:15306 at div at I (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:8129) at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:15035 at div at o (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:9891) at I (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:8129) at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:10212 at https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:13048 at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:15921 at div at https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:13048 at div at ne (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:18386) at main at https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:13048 at main at https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:13048 at t (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:194756) at Qn (https://railannouncements.co.uk/76d8c668-26bc05d90cb7623e3f0b.js:1:38431) at RecoilRoot (https://railannouncements.co.uk/76d8c668-26bc05d90cb7623e3f0b.js:1:40398) at t (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:290224) at p (https://railannouncements.co.uk/689577f30886a7ec6d84f438f5451ec0a24ddfa1-ef846d46cd58fd54c58c.js:1:2977) at be (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-37ec705af821455fa5f5.js:1:20931) at o (https://railannouncements.co.uk/component---src-pages-stations-amey-phil-sayer-tsx-df6ae0fdea26f7a861d0.js:1:488) at A (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:317613) at e at div at se (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:25302) at oe (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:25162) at ue (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:26036) at ce (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:25956) at t (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:290224) at t (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:321075) at o (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:324125) at t (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:200490) at t (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:321723) at https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:24050 at q (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:23261) at z (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:23530) at WithErrorBoundary() at ee (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:24644) at n (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:323606) at i (https://railannouncements.co.uk/app-f8f830f9ab44300b0e13.js:1:325807)

**Comment by davwheat** [comment]
I think you caught GitHub at a moment where it was down, causing an audio file to fail to load correctly.

I can't find your exact event ID, but some others around the same time as your ticket look to be related to this too.

If you can still reproduce this issue, please share a link to the announcement which breaks, and make sure you try it again without any ad blocking or privacy protection tools active (or I won't get the error report).
