### ISSUE TITLE
Error playing CRU station on phil

### ISSUE THREAD

**Issue by Boalbads** [davwheat/rail-announcements#194]
https://railannouncements.co.uk/stations/amey-phil-sayer/?announcementId=bfb29622-25eb-40b8-990e-ec0132476712
Event id: 4b17d76850604a2c9a4e9b16fdb38a54 
Detailed information:
EncodingError: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

Error: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

    at K (https://railannouncements.co.uk/9f38c194-43231ce3abd2ea088337.js:1:2532)
    at u (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:1522)
    at m (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:4325)
    at div
    at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:15308
    at div
    at I (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:8131)
    at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:15037
    at div
    at o (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:9893)
    at I (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:8131)
    at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:10214
    at https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:13736
    at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:15923
    at div
    at https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:13736
    at div
    at ne (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:18383)
    at main
    at https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:13736
    at main
    at https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:13736
    at t (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:195205)
    at Qn (https://railannouncements.co.uk/76d8c668-c01d13a149aa3b622446.js:1:38429)
    at RecoilRoot (https://railannouncements.co.uk/76d8c668-c01d13a149aa3b622446.js:1:40396)
    at t (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:287629)
    at p (https://railannouncements.co.uk/689577f30886a7ec6d84f438f5451ec0a24ddfa1-51ae9c03e0adefdf5a6f.js:1:2958)
    at be (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-b9438fab4128485b21f1.js:1:20919)
    at o (https://railannouncements.co.uk/component---src-pages-stations-amey-phil-sayer-tsx-2a9e0a98be4d9c3e8cde.js:1:488)
    at w (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:314939)
    at e
    at div
    at se (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:24792)
    at oe (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:24652)
    at ue (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:25526)
    at ce (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:25446)
    at t (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:287629)
    at t (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:318398)
    at o (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:321435)
    at t (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:200939)
    at t (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:319044)
    at https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:23540
    at J (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:22751)
    at Q (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:23020)
    at WithErrorBoundary()
    at ee (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:24134)
    at n (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:320924)
    at r (https://railannouncements.co.uk/app-082ade60a364805f4c4e.js:1:323110)

**Comment by Boalbads** [comment]
This appears to happen whenever I play phil with an announcement that has an Unknown Name

**Comment by davwheat** [comment]
![image](https://github.com/davwheat/rail-announcements/assets/7406822/3479223e-fbb6-4625-9681-bf700d4fe9ae)

**Comment by davwheat** [comment]
This is because there are missing audio files with "service from" for this TOC
