### ISSUE TITLE
Rail annouments ID 847c2fefe3554892b0a795714a532865

### ISSUE THREAD

**Issue by matthewp345** [davwheat/rail-announcements#256]
ID 847c2fefe3554892b0a795714a532865
TypeError: Cannot use 'in' operator to search for 'options' in AAP

TypeError: Cannot use 'in' operator to search for 'options' in AAP
    at https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:245357
    at Array.map (<anonymous>)
    at _t (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:245326)
    at https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:269728
    at value (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:269737)
    at to (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:70010)
    at Po (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:77489)
    at xi (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:121447)
    at bs (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:109746)
    at vs (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:109674)
    at gs (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:109537)
    at as (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:106372)
    at is (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:106754)
    at jl (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:47903)
    at cs (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:107199)
    at Le (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:17135)
    at Hr (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:39760)
    at Kn (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:24179)
    at Qn (https://railannouncements.co.uk/framework-e059e517564be6ba29f6.js:1:23963)
    at HTMLDivElement.i (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:53466)

    at n (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:247217)
    at https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:271528
    at label
    at e (https://railannouncements.co.uk/component---src-pages-amey-live-train-announcements-tsx-9eba701fb0830c9aba74.js:1:19906)
    at div
    at https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:13736
    at ce (https://railannouncements.co.uk/c1ce28a3-5d1a757f816c78722e77.js:1:9883)
    at c (https://railannouncements.co.uk/component---src-pages-amey-live-train-announcements-tsx-9eba701fb0830c9aba74.js:1:16966)
    at l (https://railannouncements.co.uk/component---src-pages-amey-live-train-announcements-tsx-9eba701fb0830c9aba74.js:1:19793)
    at main
    at https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:13736
    at main
    at https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:13736
    at t (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:188217)
    at Qn (https://railannouncements.co.uk/76d8c668-c01d13a149aa3b622446.js:1:38429)
    at RecoilRoot (https://railannouncements.co.uk/76d8c668-c01d13a149aa3b622446.js:1:40396)
    at t (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:280641)
    at p (https://railannouncements.co.uk/689577f30886a7ec6d84f438f5451ec0a24ddfa1-51ae9c03e0adefdf5a6f.js:1:2958)
    at n.default (https://railannouncements.co.uk/component---src-pages-amey-live-train-announcements-tsx-9eba701fb0830c9aba74.js:1:35370)
    at w (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:307951)
    at e
    at div
    at se (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:24792)
    at oe (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:24652)
    at ue (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:25526)
    at ce (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:25446)
    at t (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:280641)
    at t (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:311410)
    at o (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:314447)
    at t (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:193951)
    at t (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:312056)
    at https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:23540
    at J (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:22751)
    at Q (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:23020)
    at WithErrorBoundary()
    at ee (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:24134)
    at n (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:313936)
    at r (https://railannouncements.co.uk/app-94f95bebfb7e60e701a3.js:1:316122)

**Comment by davwheat** [comment]
Fixed by e64d655dcf1c8162963b31431bb35ba498e642f2
