### ISSUE TITLE
Issue with rail announcements after importing from RTT

### ISSUE THREAD

**Issue by CarolStott** [davwheat/rail-announcements#274]
I turned my adblocker off
event ID 7c8f6b8e25be49a58b20403dc8478a0b
EncodingError: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

Error: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data
at M (https://railannouncements.co.uk/9f38c194-38f7189ce90db2d52d0b.js:1:2542)
    at u (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:1522)
    at m (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:4349)
    at div
    at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:15332
    at div
    at I (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:8155)
    at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:15061
    at div
    at o (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:9917)
    at I (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:8155)
    at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:10238
    at https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:13736
    at https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:15947
    at div
    at https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:13736
    at div
    at ne (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:18407)
    at main
    at https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:13736
    at main
    at https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:13736
    at t (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:200092)
    at Qn (https://railannouncements.co.uk/76d8c668-c01d13a149aa3b622446.js:1:38429)
    at RecoilRoot (https://railannouncements.co.uk/76d8c668-c01d13a149aa3b622446.js:1:40396)
    at t (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:293225)
    at p (https://railannouncements.co.uk/689577f30886a7ec6d84f438f5451ec0a24ddfa1-51ae9c03e0adefdf5a6f.js:1:2958)
    at be (https://railannouncements.co.uk/beaa6cd174c4c823946845c5593ee41b3efafd57-bf4f1c031480b19377fc.js:1:21041)
    at o (https://railannouncements.co.uk/component---src-pages-stations-amey-celia-drummond-tsx-0fc8dabcf6891473aae7.js:1:488)
    at w (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:320535)
    at e
    at div
    at se (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:24792)
    at oe (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:24652)
    at ue (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:25526)
    at ce (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:25446)
    at t (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:293225)
    at t (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:323994)
    at o (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:327031)
    at t (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:205826)
    at t (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:324640)
    at https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:23540
    at J (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:22751)
    at Q (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:23020)
    at WithErrorBoundary()
    at ee (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:24134)
    at n (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:326520)
    at r (https://railannouncements.co.uk/app-547a15075b20f768c75e.js:1:328706)

**Comment by davwheat** [comment]
This has been fixed with an update to the website today. Thanks for reporting it!

It happens when a station from RTT isn't available in the list of announcements for Phil/Celia, which was Lockwood in this case.
